function control_colors(flag, handles)
% control_colors - Updates GUI element colors and enable states based on flags.

% Store the current flag values
setappdata(0, 'flag', flag);

% List of handle objects to be controlled
buttonHandles = [
    handles.pushbutton_update_calibration_files, ...
    handles.pushbutton_unknown_file, ...
    handles.pushbutton_decrement, ...
    handles.pushbutton_increment, ...
    handles.pushbutton_live, ...
    handles.pushbutton_process, ...
    handles.pushbutton_rotate, ...
    handles.pushbutton_clear_figures, ...
    handles.pushbutton_quit, ...
    handles.pushbutton_update_hardware_parameters, ...
    handles.edit_wavelength_min_left, ...
    handles.edit_wavelength_max_left, ...
    handles.edit_ROI_min_left, ...
    handles.edit_ROI_max_left, ...
    handles.edit_wavelength_min_right, ...
    handles.edit_wavelength_max_right, ...
    handles.edit_ROI_min_right, ...
    handles.edit_ROI_max_right
];

% Loop through handle objects and set properties based on flag
numElements = numel(buttonHandles);
for i = 1:numElements
    if flag{i} == 0
        set(buttonHandles(i), 'BackgroundColor', [0.8, 0.8, 0.8], 'Enable', 'off');
    else
        set(buttonHandles(i), 'BackgroundColor', [0, 0.8, 0], 'Enable', 'on');
    end
end