function [wra, win, deltal, templ, deltar, tempr, nincall, nincalr] = eminp (w, colers, ccnt, cnt, handles, ninl, ninr, mnrowl, mxrowl, mnrowr, mxrowr, divby, omega, lamp, conl, lam1, lam2, col, row);

load wiener

em=0;

he0 = figure('Color',[.8 .8 .8], ...
	'Colormap',mat0, ...
	'Position',[100   200   250   250], ...
    'Tag','StaticText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',9, ...
	'Position',[22 140 140 15], ...
	'String','Error Minimization',...
	'Style','text', ...
	'Tag','StaticText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',8, ...
    'Position',[22 125 140 15], ...
    'String','after Walter & Koga (2004)', ...
	'Style','text', ...
	'Tag','StaticText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',9, ...
	'Position',[30 100 80 12], ...
	'String','initial wavelength',...
	'Style','text', ...
	'Tag','StaticText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',9, ...
    'Position',[30 80 80 12], ...
    'String','band pass', ...
	'Style','text', ...
	'Tag','StaticText1');

a22 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Geneva', ...
	'FontSize',10, ...
	'Position',[120 97 30 18], ...
	'String','570', ...
	'Style','edit', ...
	'Tag','EditText1');
a23 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Geneva', ...
	'FontSize',10, ...
	'Position',[120 77 30 18], ...
	'String','200', ...
	'Style','edit', ...
	'Tag','EditText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
	'FontSize',9, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[60 40 50 20], ...
	'String','Start', ...
	'Callback','uiresume(gcbf)', ...
    'HandleVisibility', 'off',...
	'Tag','Pushbutton1');

uiwait
   
win=(eval(get(a22,'string')));
wra=(eval(get(a23,'string')));
em=0;

close Figure 1;

[templ, deltal, nincall] = eminfunpl (w, colers, ccnt, cnt, handles, em, win, wra, ninl, mnrowl, mxrowl, divby, omega, lamp, conl, lam1, lam2, col, row);
em=0;
[tempr, deltar, nincalr] = eminfunpr (w, colers, ccnt, cnt, handles, em, win, wra, ninr, mnrowr, mxrowr, divby, omega, lamp, conl, lam1, lam2, col, row);


