function [templ, deltal, jl] = eminfunl (colers, ccnt, cnt, handles, em, win, wra, ninl, mnrowl, mxrowl, divby, omega, lamp, conl, lam1, lam2, col, row);

load wiener;

rp=0;
clear tempec; clear deltec; clear aveerr;

mnll=win;
mxll=mnll+wra;
xrange=(1:row);

lc=0;
avemin=1000;

scrsz = get(0,'ScreenSize');
if (em==0)
    hel = figure('Color',[.8 .8 .8], ...
	'Colormap',mat0, ...
    'Name','Error Minimisation left', ...
	'Position',[100   80   500   600], ...
    'Tag','errmin left')
end;

while (mxll<850)
    lc=lc+1;
    mn(lc)=mnll;
    mx(lc)=mxll;
    
    nin = ninl;
    mnlam = mnll;
    mxlam = mxll;
    mnrow = mnrowl;
    mxrow = mxrowl;
    
	[tempec(lc,:),j,etemp,deltec(lc,:)] = wientemp(nin,divby,omega,lamp,conl,lam1,lam2,mxlam,mnlam,mxrow,mnrow,col);
    mnll=mnll+10;
    mxll=mxll+10;
    aveerr_left(lc)=nanmean(deltec(lc,mnrowl:mxrowl));
    
    if(aveerr_left(lc)<avemin); 
        avemin=aveerr_left(lc);
        amc=lc
    end;
   
    templ = tempec(amc,:);
    jl = j;
    etempl = etemp;
    deltal = deltec(amc,:); 
    
figure(hel)
subplot('position',[0.18,0.72,0.75,0.25])
plot(aveerr_left);
grid on;
xlabel('iteration #');
ylabel('ave error');
set(gca,'NextPlot','replacechildren')

subplot('position',[0.18,0.18,0.75,0.45])
errorbar(xrange(mnrowl:mxrowl),tempec(amc,mnrowl:mxrowl),deltec(amc,mnrowl:mxrowl),colers(ccnt));
grid on;
xlabel('pixel'), ylabel('Temp (K)')
set(gca,'NextPlot','add');

end;

amcs=num2str(amc);
mns=num2str(mn(amc));
mxs=num2str(mx(amc));

he2 = uicontrol('Parent',hel, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[10 20 120 18], ...
    'String','minimum error at iteration', ...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',hel, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[130 20 12 18], ...
    'String',amcs, ...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',hel, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[170 20 20 18], ...
    'String',mns,...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',hel, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[190 20 10 18], ...
    'String','-',...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',hel, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[200 20 20 18], ...
    'String',mxs, ...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',hel, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[220 20 20 18], ...
    'String','nm', ...
	'Style','text', ...
	'Tag','StaticText1');

heq = uicontrol('Parent',hel, ...
	'Units','points', ...
	'FontName','Geneva', ...
	'FontSize',9, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[300 20 50 20], ...
	'String','Accept', ...
    'Callback','uiresume(gcbf)', ...
    'HandleVisibility', 'off',...
	'Tag','Pushbutton11');

uiwait

avetempl(cnt)=mean(templ(mnrowl:mxrowl));
erravel(cnt)=nanmean(deltal(mnrowl:mxrowl));
maxtempl(cnt)=max(templ(mnrowl:mxrowl));
mintempl(cnt)=min(templ(mnrowl:mxrowl));
stdtempl(cnt)=std(templ(mnrowl:mxrowl));

set(handles.edit7,'string',mn(amc));
set(handles.edit8,'string',mx(amc));

lpixl=round(conl + lam1.*mnll + lam2.*mnll.^2);
hpixl=round(conl + lam1.*mxll + lam2.*mxll.^2);
xrange=(1:row);

if hpixl>1024
    hpixl=1024;
end;

plot(handles.axes3, omega(lpixl:hpixl),jl(lpixl:hpixl,mnrowl:mxrowl),'b');

errorbar(handles.axes1, xrange(mnrowl:mxrowl),tempec(amc,mnrowl:mxrowl),deltec(amc,mnrowl:mxrowl),colers(ccnt));
grid(handles.axes1,'on');
set(handles.axes1,'NextPlot','add');
set(handles.text22,'string',maxtempl(cnt));
set(handles.text26,'string',erravel(cnt));
close Figure 1;

em=em+1;




