function [wra, win, templ, deltal, tempr, deltar, omega, jr, jl] = emin (ccnt, handles);

ninl = getappdata(0,'ninl');
ninr = getappdata(0,'ninr');
mnrowl = getappdata(0,'mnrowl');
mxrowl = getappdata(0,'mxrowl');
mnrowr = getappdata(0,'mnrowr');
mxrowr = getappdata(0,'mxrowr');
divby = getappdata(0,'divby');
omega = getappdata(0,'omega');
lamp = getappdata(0,'lamp');
conl = getappdata(0,'conl');
lam1 = getappdata(0,'lam1');
lam2 = getappdata(0,'lam2');
col = getappdata(0,'col');
row = getappdata(0,'row');
cnt = getappdata(0,'cnt');
colers = getappdata(0,'colers');

em=0;

load wiener;

he0 = figure('Color',[.8 .8 .8], ...
	'Colormap',mat0, ...
	'Position',[100   200   250   250], ...
    'Tag','StaticText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',9, ...
	'Position',[22 140 140 15], ...
	'String','Error Minimization',...
	'Style','text', ...
	'Tag','StaticText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',8, ...
    'Position',[22 125 140 15], ...
    'String','after Walter & Koga (2004)', ...
	'Style','text', ...
	'Tag','StaticText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',9, ...
	'Position',[30 100 80 12], ...
	'String','initial wavelength',...
	'Style','text', ...
	'Tag','StaticText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',9, ...
    'Position',[30 80 80 12], ...
    'String','band pass', ...
	'Style','text', ...
	'Tag','StaticText1');

a22 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Geneva', ...
	'FontSize',10, ...
	'Position',[120 97 30 18], ...
	'String','570', ...
	'Style','edit', ...
	'Tag','EditText1');
a23 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Geneva', ...
	'FontSize',10, ...
	'Position',[120 77 30 18], ...
	'String','200', ...
	'Style','edit', ...
	'Tag','EditText1');

he1 = uicontrol('Parent',he0, ...
	'Units','points', ...
	'FontName','Geneva', ...
	'FontSize',9, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[60 40 50 20], ...
	'String','Start', ...
	'Callback','uiresume(gcbf)', ...
    'HandleVisibility', 'off',...
	'Tag','Pushbutton1');

uiwait
   
win=(eval(get(a22,'string')));
wra=(eval(get(a23,'string')));
em=0;

close Figure 1;

[templ, deltal, jl] = eminfunl (colers, ccnt, cnt, handles, em, win, wra, ninl, mnrowl, mxrowl, divby, omega, lamp, conl, lam1, lam2, col, row);
em=0;
[tempr, deltar, jr] = eminfunr (colers, ccnt, cnt, handles, em, win, wra, ninr, mnrowr, mxrowr, divby, omega, lamp, conl, lam1, lam2, col, row);






