function [tempr, deltar, nincalr] = eminfunpr (w, colers, ccnt, cnt, handles, em, win, wra, ninr, mnrowr, mxrowr, divby, omega, lamp, conl, lam1, lam2, col, row);

load wiener

rp=0;
clear tempec; clear deltec; clear aveerr;

mnll=win; 
mxll=mnll+wra;
xrange=(1:row);

lc=0;
avemin=1000;

scrsz = get(0,'ScreenSize');
if (em==0)
    her = figure('Color',[.8 .8 .8], ...
	'Colormap',mat0, ...
    'Name','Error Minimisation Right', ...
	'Position',[scrsz(3)-600    80   500   600], ...
    'Tag','errmin right')
end;

while (mxll<850)
    lc=lc+1;
    mn(lc)=mnll;
    mx(lc)=mxll;
    
    nin = ninr;
    mnlam = mnll;
    mxlam = mxll;
    mnrow = mnrowr;
    mxrow = mxrowr;
    
    [tempec(lc,:),emmi,deltec(lc,:),nincal] = plancktemp(nin,w,lamp,conl,lam1,lam2,mxlam,mnlam,mxrow,mnrow,col);
    mnll=mnll+10;
    mxll=mxll+10;
    aveerr_Right(lc)=mean(deltec(lc,mnrowr:mxrowr));
    
    if(aveerr_Right(lc)<avemin);
        avemin=aveerr_Right(lc);
        amc=(lc);
    end;
    
    tempr=tempec(amc,:);
    emmir=emmi
    deltar=deltec(amc,:);
    nincalr=nincal;
    
figure(her)
subplot('position',[0.18,0.72,0.75,0.25])
plot(aveerr_Right);
grid on;
xlabel('iteration #');
ylabel('ave error');
set(gca,'NextPlot','replacechildren')


subplot('position',[0.18,0.18,0.75,0.45])
errorbar(xrange(mnrowr:mxrowr),tempec(amc,mnrowr:mxrowr),deltec(amc,mnrowr:mxrowr),colers(ccnt));
grid on;
xlabel('pixel'), ylabel('Temp (K)')
set(gca,'NextPlot','add');

end;

amcs=num2str(amc);
mns=num2str(mn(amc));
mxs=num2str(mx(amc));

he2 = uicontrol('Parent',her, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[10 20 120 18], ...
    'String','minimum error at iteration', ...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',her, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[130 20 12 18], ...
    'String',amcs, ...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',her, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[170 20 20 18], ...
    'String',mns,...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',her, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[190 20 10 18], ...
    'String','-',...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',her, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[200 20 20 18], ...
    'String',mxs, ...
	'Style','text', ...
	'Tag','StaticText1');

he2 = uicontrol('Parent',her, ...
	'Units','points', ...
	'FontName','Geneva', ...
    'ForegroundColor',[0 0 0], ...
	'FontSize',10, ...
    'Position',[220 20 20 18], ...
    'String','nm', ...
	'Style','text', ...
	'Tag','StaticText1');


he2 = uicontrol('Parent',her, ...
	'Units','points', ...
	'FontName','Geneva', ...
	'FontSize',9, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[300 20 50 20], ...
	'String','Accept', ...
    'Callback','uiresume(gcbf)', ...
    'HandleVisibility', 'off',...
	'Tag','Pushbutton11');

uiwait

avetempr(cnt)=mean(tempr(mnrowr:mxrowr));
erraver(cnt)=mean(deltar(mnrowr:mxrowr));
maxtempr(cnt)=max(tempr(mnrowr:mxrowr));
mintempr(cnt)=min(tempr(mnrowr:mxrowr));
stdtempr(cnt)=std(tempr(mnrowr:mxrowr));

set(handles.edit15,'string',mn(amc));
set(handles.edit16,'string',mx(amc));

lpixr=round(conl + lam1.*mnll + lam2.*mnll.^2);
hpixr=round(conl + lam1.*mxll + lam2.*mxll.^2);
xrange=(1:row);

if hpixr>1024
   hpixr=1024;
end;

plot(handles.axes4, w(lpixr:hpixr),nincalr(lpixr:hpixr,mnrowr:mxrowr),'b');

errorbar(handles.axes2, xrange(mnrowr:mxrowr),tempec(amc,mnrowr:mxrowr),deltec(amc,mnrowr:mxrowr),colers(ccnt));
grid(handles.axes2,'on');
set(handles.axes2,'NextPlot','add');
set(handles.text24,'string',maxtempr(cnt));
set(handles.text28,'string',erraver(cnt));
close Figure 1;

em=em+1;
